export type model =
  | "dall-e"
  | "stable-diffusion-xl"
  | "stability-sd3-turbo"
  | "playground-v2"
  | "playground-v2-5"
  | "bria.ai"
  | "d-id"
  | "chatgpt"
  | "flux-schnell"
  |"runway-ml"
  |"tavus"
  |"imagen"